<?php

namespace Deryko\MappingSelect;

use Laravel\Nova\Fields\Field;
use Laravel\Nova\Http\Requests\NovaRequest;

class MappingSelect extends Field
{
    /**
     * The field's component.
     *
     * @var string
     */
    public $component = 'mapping-select';

    protected function fillAttributeFromRequest(NovaRequest $request, $requestAttribute, $model, $attribute)
    {
        $model->land_mark = $request['land_mark'];
        $model->latitude = $request['latitude'];
        $model->longitude = $request['longitude'];
        parent::fillAttributeFromRequest($request, $requestAttribute, $model, $attribute); // TODO: Change the autogenerated stub
    }
}
